let projectId = localStorage.getItem('claimledger.projectId') || '';
const $ = (id) => document.getElementById(id);
async function api(path, options = {}) { const res = await fetch(path, { headers: { 'content-type': 'application/json' }, ...options }); if (!res.ok) throw new Error((await res.json()).error || res.statusText); return res.json(); }
function setProject(id) { projectId = id; localStorage.setItem('claimledger.projectId', id); $('current').textContent = `Current project: ${id}`; }
async function refresh() { if (!projectId) return; const claims = await api(`/api/claims?project_id=${projectId}`); const spans = await api('/api/evidence-spans'); $('claims').innerHTML = claims.map(c => `<tr><td class="status ${c.status}">${c.status}</td><td>${escapeHtml(c.claim_text)}</td><td>${c.claim_type}<br><span class="small">score ${Number(c.evidence_score).toFixed(2)} · ${c.source}</span></td><td>${c.evidence_span_ids.map(id => escapeHtml(spans.find(s=>s.id===id)?.quote||id)).join('<hr>')}</td><td><button class="ok" onclick="approve('${c.id}')">Approve</button> <button onclick="editClaim('${c.id}')">Edit</button> <button class="danger" onclick="decline('${c.id}')">Decline</button></td></tr>`).join(''); const audit = await api(`/api/audit-events?project_id=${projectId}`); $('audit').innerHTML = audit.slice(-12).reverse().map(e => `${e.created_at} · ${e.event_type} · ${e.entity_type}:${e.entity_id}`).join('<br>'); }
$('ingest').onclick = async () => { const project = await api('/api/projects', { method: 'POST', body: JSON.stringify({ name: $('project').value }) }); setProject(project.id); await api('/api/source-documents', { method: 'POST', body: JSON.stringify({ project_id: project.id, kind: $('kind').value, filename: $('filename').value, text: $('source').value }) }); await refresh(); };
$('extract').onclick = async () => { await api('/api/claims', { method: 'POST', body: JSON.stringify({ project_id: projectId }) }); await refresh(); };
window.approve = async (id) => { await api(`/api/claims/${id}/approve`, { method: 'POST', body: '{}' }); await refresh(); };
window.decline = async (id) => { await api(`/api/claims/${id}/decline`, { method: 'POST', body: '{}' }); await refresh(); };
window.editClaim = async (id) => { const claim_text = prompt('Edit claim text'); if (claim_text) { await api(`/api/claims/${id}`, { method: 'PATCH', body: JSON.stringify({ claim_text }) }); await refresh(); } };
$('generate').onclick = async () => { const claims = (await api(`/api/claims?project_id=${projectId}`)).filter(c => c.status === 'approved'); if (!claims.length) return alert('Approve at least one claim first.'); const bullet = await api('/api/bullets', { method: 'POST', body: JSON.stringify({ project_id: projectId, claim_ids: [claims[0].id], tone: 'technical' }) }); await api(`/api/bullets/${bullet.id}`, { method: 'PATCH', body: '{}' }); alert('Bullet created. Approve it via API in this MVP; integration test covers export gate.'); await refresh(); };
$('export').onclick = async () => { const out = await api(`/api/tailoring-runs/${projectId}/export`, { method: 'POST', body: JSON.stringify({ title: 'Synthetic Target Role' }) }); $('exportResult').textContent = JSON.stringify(out, null, 2); await refresh(); };
function escapeHtml(s) { return String(s).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
if (projectId) setProject(projectId); refresh();
